# Kickoff default config

# Characters shown in front of the query.
prompt = 'Î»  '

# space between window border and the content in pixel
padding = 100

# font = ''        # has been deprecated in favour of fonts list
fonts = ['Noto Sans Mono']     # list of otf or ttf fonts. later elements work as fallback
font_size = 32.0

[history]
decrease_interval = 48 # interval to decrease the number of launches

[colors]
# color format: rgb or rgba, if transparency is desired
background = '#02010aaa'
prompt = '#390daaff'
text = '#c8c5c4ff'          # for search results
text_query = '#9f89aaff'    # for the search query
text_selected = '#390daaff' # for the currently selected result

[keybindings]
# keybindings syntax: ctrl/shift/alt/logo as modifiers and a key joined by '+' signs
# A list of available keys can be found here: https://docs.rs/crate/x11-keysymdef/0.2.0/source/src/keysym.json
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_down = ["ctrl+j"]
nav_up = ["ctrl+k"]
exit = ["Escape"]
